export type Candle = { t: string; o: number; h: number; l: number; c: number; v: number };
export type SeriesPoint = { t: string; c: number };
export function isRecord(value: unknown): value is Record<string, unknown> { return typeof value === "object" && value !== null && !Array.isArray(value); }
export function num(value: unknown): number | null { if (typeof value === "number" && Number.isFinite(value)) return value; if (typeof value === "string" && value.trim() !== "" && Number.isFinite(Number(value))) return Number(value); return null; }
export function str(value: unknown): string | null { if (typeof value === "string" && value.length > 0) return value; if (typeof value === "number") return String(value); return null; }
export function rows(raw: unknown): Record<string, unknown>[] { return Array.isArray(raw) ? raw.filter(isRecord) : []; }
export function toCandles(raw: unknown): Candle[] { return rows(raw).map(row => ({ t: str(row.Date) ?? str(row.Datetime) ?? str(row.index) ?? "", o: num(row.Open) ?? 0, h: num(row.High) ?? 0, l: num(row.Low) ?? 0, c: num(row.Close) ?? 0, v: num(row.Volume) ?? 0 })).filter(point => point.c > 0 && point.t).sort((a, b) => a.t.localeCompare(b.t)); }
export function toSeries(raw: unknown, valueKey: string): SeriesPoint[] { return rows(raw).map(row => ({ t: str(row.Date) ?? str(row.index) ?? "", c: num(row[valueKey]) ?? 0 })).filter(point => point.c !== 0 && point.t).sort((a, b) => a.t.localeCompare(b.t)); }
export type StatementTable = { columns: string[]; rows: { label: string; values: (number | null)[] }[] };
export function toStatementTable(raw: unknown, preferred: string[]): StatementTable { const list = rows(raw); if (!list.length) return { columns: [], rows: [] }; const periodSet = new Set<string>(); list.forEach(row => Object.keys(row).forEach(key => { if (key !== "index") periodSet.add(key); })); const columns = Array.from(periodSet).sort().reverse().slice(0, 5); const byLabel = new Map<string, Record<string, unknown>>(); list.forEach(row => { const label = str(row.index); if (label) byLabel.set(label, row); }); const labels = Array.from(byLabel.keys()); const ordered = [...preferred.filter(label => byLabel.has(label)), ...labels.filter(label => !preferred.includes(label)).sort()]; return { columns: columns.map(column => column.slice(0, 10)), rows: ordered.map(label => ({ label, values: columns.map(column => num(byLabel.get(label)?.[column])) })).filter(row => row.values.some(value => value !== null)) }; }
export type GenericTable = { columns: string[]; rows: Record<string, string>[] };
export function toGenericTable(raw: unknown, limit = 50, drop: string[] = ["index"]): GenericTable { const list = rows(raw).slice(0, limit); const columns: string[] = []; list.forEach(row => Object.keys(row).forEach(key => { if (!drop.includes(key) && !columns.includes(key)) columns.push(key); })); return { columns, rows: list.map(row => Object.fromEntries(columns.map(column => { const value = row[column]; const formatted = value === null || value === undefined ? "—" : typeof value === "number" ? (Number.isInteger(value) ? value.toLocaleString() : value.toLocaleString(undefined, { maximumFractionDigits: 4 })) : String(value).slice(0, 120); return [column, formatted]; }))) }; }
export function normalizeCurrency(value: string | null | undefined) { return (value ?? "USD").trim().toUpperCase() || "USD"; }
export function normalizeNullableNumber(value: unknown): number | null { return num(value); }
export function normalizePercent(value: number | null | undefined, fractional = false) { if (value === null || value === undefined || !Number.isFinite(value)) return null; return fractional ? value * 100 : value; }
