import { BarChart3, Bell, ChevronRight, Flame, Globe, LineChart, Menu, Newspaper, PanelLeftClose, Search, Settings, SlidersHorizontal, Sparkles, Star, TrendingUp, X } from "lucide-react";
import { useState, type ReactNode } from "react";
import { Link, useLocation } from "wouter";
import { TickerAutocomplete } from "@/components/finance/TickerAutocomplete";

const primary = [{ label: "Search", icon: Search }, { label: "Watchlist", icon: Star }, { label: "Markets", icon: TrendingUp, active: true }, { label: "Pro Screener", icon: SlidersHorizontal }, { label: "AI Analyst", icon: Sparkles, href: "/chat" }, { label: "Market News", icon: Newspaper }, { label: "Alerts", icon: Bell }];
const research = [{ label: "Market Movers", icon: Flame }, { label: "ETF Screener", icon: BarChart3 }, { label: "Sectors", icon: Globe }, { label: "Global Markets", icon: TrendingUp }];
function NavGroup({ label, items }: { label?: string; items: typeof primary }) { return <section className="terminal-nav-group">{label && <p>{label}</p>}{items.map(item => { const Icon = item.icon; const content = <><Icon size={16}/><span>{item.label}</span>{item.label === "Watchlist" && <i>0</i>}</>; return item.href ? <Link key={item.label} href={item.href} className="terminal-nav-item">{content}</Link> : <button key={item.label} className={`terminal-nav-item ${item.active ? "active" : ""}`}>{content}</button>; })}</section>; }
export function DashboardShell({ children }: { children: ReactNode }) {
  const [mobileOpen, setMobileOpen] = useState(false); const [collapsed, setCollapsed] = useState(false); const [location] = useLocation();
  const side = <aside className={`terminal-sidebar ${collapsed ? "collapsed" : ""} ${mobileOpen ? "open" : ""}`}><div className="terminal-brand"><span><LineChart size={16}/></span><div><b>Screener Terminal</b><small>Pro · Live Data</small></div></div><NavGroup items={primary}/><NavGroup label="Screener presets" items={[{ label: "Top Gainers", icon: TrendingUp }, { label: "Top Losers", icon: TrendingUp }, { label: "Most Active", icon: BarChart3 }]}/><NavGroup label="Research tools" items={research}/><NavGroup label="Markets" items={[{ label: "US Equities", icon: TrendingUp }, { label: "ETFs", icon: BarChart3 }, { label: "Crypto", icon: Globe }, { label: "Forex", icon: Globe }]}/><div className="terminal-bottom"><button className="terminal-nav-item"><Settings size={16}/><span>Settings</span></button></div></aside>;
  return <div className="terminal-shell">{side}{mobileOpen && <button className="terminal-backdrop" aria-label="Close navigation" onClick={() => setMobileOpen(false)}/>}<div className="terminal-workspace"><header className="terminal-topbar"><button className="terminal-icon-button mobile-only" onClick={() => setMobileOpen(true)} aria-label="Open navigation"><Menu size={17}/></button><button className="terminal-icon-button desktop-only" onClick={() => setCollapsed(value => !value)} aria-label="Collapse navigation"><PanelLeftClose size={17}/></button><div className="terminal-crumb"><span>Personal Terminal</span><ChevronRight size={14}/><b>{location === "/" ? "Markets" : "Markets"}</b></div><div className="terminal-top-search"><TickerAutocomplete compact placeholder="Search markets"/></div><span className="terminal-live"><i/> Live</span></header><main className="terminal-scroll"><div className="terminal-content">{children}</div></main></div></div>;
}
