import { BarChart3, Bell, ChevronRight, Flame, Globe, LineChart, Menu, Newspaper, PanelLeftClose, Search, Settings, SlidersHorizontal, Sparkles, Star, TrendingUp } from "lucide-react";
import { useState, type ReactNode } from "react";
import { TickerAutocomplete } from "@/components/finance/TickerAutocomplete";

export type TerminalPage = string;
type Item = { id: TerminalPage; label: string; icon: typeof Search };
const primary: Item[] = [{ id: "search", label: "Search", icon: Search }, { id: "watchlist", label: "Watchlist", icon: Star }, { id: "markets", label: "Markets", icon: TrendingUp }, { id: "proscreener", label: "Pro Screener", icon: SlidersHorizontal }, { id: "ai", label: "AI Analyst", icon: Sparkles }, { id: "news", label: "Market News", icon: Newspaper }, { id: "alerts", label: "Alerts", icon: Bell }];
const research: Item[] = [{ id: "movers", label: "Market Movers", icon: Flame }, { id: "etfscreener", label: "ETF Screener", icon: BarChart3 }, { id: "sectors", label: "Sectors", icon: Globe }, { id: "globalmarkets", label: "Global Markets", icon: TrendingUp }];
function NavGroup({ label, items, page, onNavigate }: { label?: string; items: Item[]; page: TerminalPage; onNavigate: (page: TerminalPage) => void }) { return <section className="terminal-nav-group">{label && <p>{label}</p>}{items.map(item => { const Icon = item.icon; return <button key={item.id} className={`terminal-nav-item ${page === item.id ? "active" : ""}`} onClick={() => onNavigate(item.id)}><Icon size={16}/><span>{item.label}</span>{item.id === "watchlist" && <i>0</i>}</button>; })}</section>; }
export function DashboardShell({ page, onNavigate, children }: { page: TerminalPage; onNavigate: (page: TerminalPage) => void; children: ReactNode }) { const [mobileOpen, setMobileOpen] = useState(false); const [collapsed, setCollapsed] = useState(false); const side = <aside className={`terminal-sidebar ${collapsed ? "collapsed" : ""} ${mobileOpen ? "open" : ""}`}><div className="terminal-brand"><span><LineChart size={16}/></span><div><b>Screener Terminal</b><small>Pro · Live Data</small></div></div><NavGroup items={primary} page={page} onNavigate={value => { onNavigate(value); setMobileOpen(false); }}/><NavGroup label="Screener presets" items={[{ id: "movers-gainers", label: "Top Gainers", icon: TrendingUp }, { id: "movers-losers", label: "Top Losers", icon: TrendingUp }, { id: "movers-active", label: "Most Active", icon: BarChart3 }]} page={page} onNavigate={onNavigate}/><NavGroup label="Research tools" items={research} page={page} onNavigate={onNavigate}/><NavGroup label="Markets" items={[{ id: "equities", label: "US Equities", icon: TrendingUp }, { id: "etfs", label: "ETFs", icon: BarChart3 }, { id: "crypto", label: "Crypto", icon: Globe }, { id: "forex", label: "Forex", icon: Globe }]} page={page} onNavigate={onNavigate}/><div className="terminal-bottom"><button className={`terminal-nav-item ${page === "settings" ? "active" : ""}`} onClick={() => onNavigate("settings")}><Settings size={16}/><span>Settings</span></button></div></aside>; return <div className="terminal-shell">{side}{mobileOpen && <button className="terminal-backdrop" aria-label="Close navigation" onClick={() => setMobileOpen(false)}/>}<div className="terminal-workspace"><header className="terminal-topbar"><button className="terminal-icon-button mobile-only" onClick={() => setMobileOpen(true)} aria-label="Open navigation"><Menu size={17}/></button><button className="terminal-icon-button desktop-only" onClick={() => setCollapsed(value => !value)} aria-label="Collapse navigation"><PanelLeftClose size={17}/></button><div className="terminal-crumb"><span>Personal Terminal</span><ChevronRight size={14}/><b>{page === "markets" ? "Markets" : page.replace(/-/g, " ")}</b></div><div className="terminal-top-search"><TickerAutocomplete compact placeholder="Search markets"/></div><span className="terminal-live"><i/> Live</span></header><main className="terminal-scroll"><div className="terminal-content">{children}</div></main></div></div>; }
