import { FormEvent, useState } from "react";
import { ExternalLink, Plus, Search, Trash2 } from "lucide-react";
import { QuoteTable } from "./QuoteTable";
import type { FinanceQuote } from "@/lib/finance-types";
import { useAppState } from "@/contexts/AppStateContext";
import { trpc } from "@/lib/trpc";

export function WatchlistView() { const { watchSymbols } = useAppState(); const { data = [] } = trpc.finance.quotes.useQuery({ symbols: watchSymbols.length ? watchSymbols : ["AAPL"] }); return <section className="terminal-view"><div className="terminal-view-heading"><div><p>Personal list</p><h2>Watchlist</h2></div><span>{watchSymbols.length} symbols</span></div><QuoteTable quotes={data as FinanceQuote[]} title=""/></section>; }
export function NewsView() { const { data: news = [] } = trpc.finance.news.useQuery({ symbol: "AAPL" }); return <section className="terminal-view"><div className="terminal-view-heading"><div><p>Market context</p><h2>Market news</h2></div><span>Live feeds</span></div><div className="terminal-news-grid">{news.map(item => <a key={item.link} href={item.link} target="_blank" rel="noreferrer"><b>{item.title}</b><span>{item.publisher}</span><ExternalLink size={13}/></a>)}</div></section>; }
export function AlertsView() { const { alerts, addAlert, removeAlert } = useAppState(); const [symbol, setSymbol] = useState("AAPL"); const [price, setPrice] = useState(250); const submit = (event: FormEvent) => { event.preventDefault(); if (symbol.trim() && price > 0) addAlert(symbol.trim().toUpperCase(), price, true); }; return <section className="terminal-view"><div className="terminal-view-heading"><div><p>Notifications</p><h2>Price alerts</h2></div></div><form className="terminal-alert-form" onSubmit={submit}><input value={symbol} onChange={event => setSymbol(event.target.value)} placeholder="Ticker"/><input type="number" value={price} onChange={event => setPrice(Number(event.target.value))} min="0" step="0.01"/><button><Plus size={14}/> Add alert</button></form><div className="terminal-alerts">{alerts.map(alert => <article key={alert.id}><span>{alert.symbol}</span><b>{alert.above ? "Above" : "Below"} ${alert.price}</b><button onClick={() => removeAlert(alert.id)} aria-label="Remove alert"><Trash2 size={14}/></button></article>)}{!alerts.length && <p>No alerts yet. Add a price threshold to begin monitoring.</p>}</div></section>; }
export function SettingsView() { const { theme, setTheme, market, setMarket, assetClass, setAssetClass } = useAppState(); return <section className="terminal-view"><div className="terminal-view-heading"><div><p>Workspace</p><h2>Settings</h2></div></div><div className="terminal-settings"><p>Appearance</p><div>{(["terminal", "light", "paper", "neuborder"] as const).map(value => <button key={value} className={theme === value ? "active" : ""} onClick={() => setTheme(value)}>{value}</button>)}</div><p>Market scope</p><div>{(["US", "IN"] as const).map(value => <button key={value} className={market === value ? "active" : ""} onClick={() => setMarket(value)}>{value}</button>)}</div><p>Asset class</p><div>{(["equities", "etfs", "crypto", "forex"] as const).map(value => <button key={value} className={assetClass === value ? "active" : ""} onClick={() => setAssetClass(value)}>{value}</button>)}</div></div></section>; }
export function MoversView({ mode, quotes }: { mode: "gainers" | "losers" | "active" | "all"; quotes: FinanceQuote[] }) { const sorted = [...quotes].sort((a, b) => mode === "active" ? (b.volume ?? 0) - (a.volume ?? 0) : mode === "losers" ? (a.changePercent ?? 0) - (b.changePercent ?? 0) : (b.changePercent ?? 0) - (a.changePercent ?? 0)); const title = mode === "gainers" ? "Top gainers" : mode === "losers" ? "Top losers" : mode === "active" ? "Most active" : "Market movers"; return <section className="terminal-view"><div className="terminal-view-heading"><div><p>Market activity</p><h2>{title}</h2></div><span>Live quotes</span></div><div className="terminal-view-table"><QuoteTable quotes={sorted} title=""/></div></section>; }
export function ScreenerView({ title, quotes }: { title: string; quotes: FinanceQuote[] }) { const [filter, setFilter] = useState(""); const visible = quotes.filter(quote => `${quote.symbol} ${quote.name}`.toLowerCase().includes(filter.toLowerCase())); return <section className="terminal-view"><div className="terminal-view-heading"><div><p>Research filter</p><h2>{title}</h2></div><span>{visible.length} matches</span></div><div className="terminal-screener-filter"><Search size={15}/><input value={filter} onChange={event => setFilter(event.target.value)} placeholder="Filter symbols or company names"/></div><div className="terminal-view-table"><QuoteTable quotes={visible} title=""/></div></section>; }
