/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as StockSymbolRouteImport } from './routes/stock.$symbol'
import { Route as ApiCloudAuthRouteImport } from './routes/api/cloud/auth'
import { Route as ApiCloudStateRouteImport } from './routes/api/cloud/state'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const StockSymbolRoute = StockSymbolRouteImport.update({
  id: '/stock/$symbol',
  path: '/stock/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCloudAuthRoute = ApiCloudAuthRouteImport.update({
  id: '/api/cloud/auth',
  path: '/api/cloud/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCloudStateRoute = ApiCloudStateRouteImport.update({
  id: '/api/cloud/state',
  path: '/api/cloud/state',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/compare': typeof CompareRoute
  '/api/chat': typeof ApiChatRoute
  '/stock/$symbol': typeof StockSymbolRoute
  '/api/cloud/auth': typeof ApiCloudAuthRoute
  '/api/cloud/state': typeof ApiCloudStateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/compare': typeof CompareRoute
  '/api/chat': typeof ApiChatRoute
  '/stock/$symbol': typeof StockSymbolRoute
  '/api/cloud/auth': typeof ApiCloudAuthRoute
  '/api/cloud/state': typeof ApiCloudStateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/compare': typeof CompareRoute
  '/api/chat': typeof ApiChatRoute
  '/stock/$symbol': typeof StockSymbolRoute
  '/api/cloud/auth': typeof ApiCloudAuthRoute
  '/api/cloud/state': typeof ApiCloudStateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/compare'
    | '/api/chat'
    | '/stock/$symbol'
    | '/api/cloud/auth'
    | '/api/cloud/state'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/compare'
    | '/api/chat'
    | '/stock/$symbol'
    | '/api/cloud/auth'
    | '/api/cloud/state'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/compare'
    | '/api/chat'
    | '/stock/$symbol'
    | '/api/cloud/auth'
    | '/api/cloud/state'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  CompareRoute: typeof CompareRoute
  ApiChatRoute: typeof ApiChatRoute
  StockSymbolRoute: typeof StockSymbolRoute
  ApiCloudAuthRoute: typeof ApiCloudAuthRoute
  ApiCloudStateRoute: typeof ApiCloudStateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock/$symbol': {
      id: '/stock/$symbol'
      path: '/stock/$symbol'
      fullPath: '/stock/$symbol'
      preLoaderRoute: typeof StockSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cloud/auth': {
      id: '/api/cloud/auth'
      path: '/api/cloud/auth'
      fullPath: '/api/cloud/auth'
      preLoaderRoute: typeof ApiCloudAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cloud/state': {
      id: '/api/cloud/state'
      path: '/api/cloud/state'
      fullPath: '/api/cloud/state'
      preLoaderRoute: typeof ApiCloudStateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  CompareRoute: CompareRoute,
  ApiChatRoute: ApiChatRoute,
  StockSymbolRoute: StockSymbolRoute,
  ApiCloudAuthRoute: ApiCloudAuthRoute,
  ApiCloudStateRoute: ApiCloudStateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
